### PR TITLE
Fix bugs in mate processing

### PR DESCRIPTION
**Pull request by kvid**
The code processing mates used a mix of repeated connector look-ups and local connector variables, and one variable was used before it was assigned the correct value.

This error was detected when investigating the #355 bug report.

- [x] The local connector variables are now both assigned initially when processing each mate, and used instead of repeated connector look-ups.
- [x] The same code section also had an unfortunate side-effect - observed in https://github.com/wireviz/WireViz/issues/325#issuecomment-2116395221
that caused some generated dot output to be unavailable for tweaking. A fix for that is now pushed as a separate commit into this PR.

### CODE REVIEW

**Comment by amotl** [comment]
Reviewing this patch may need your attention, @formatc1702. Do you have a few spare cycles?

**Comment by kvid** [comment]
@formatc1702 - Please review, but not merge yet this PR.

**Comment by formatc1702** [comment]
Set to draft to prevent premature merge as requested :)

**Review by formatc1702 — APPROVED** [review]
Good fix, thanks!

**Pull request merged**
